CREATE TABLE competitor
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    surname      VARCHAR(255)                            NOT NULL,
    age          INT,
    gender       VARCHAR(255),
    competition  VARCHAR(255),
    club         VARCHAR(255)                            NOT NULL,
    advancement  INT,
    weight       INT,
    skipped_last BOOLEAN,
    CONSTRAINT pk_competitor PRIMARY KEY (id)
);