CREATE TABLE duel
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    participant1 BIGINT,
    participant2 BIGINT,
    winner       BIGINT,
    position     INT,
    round        INT,
    branch       VARCHAR(255),
    duel_id      BIGINT,
    CONSTRAINT pk_duel PRIMARY KEY (id)
);

ALTER TABLE duel
    ADD CONSTRAINT FK_DUEL_ON_DUEL FOREIGN KEY (duel_id) REFERENCES tournament (id);
