ALTER TABLE TOURNAMENT
ADD tournamentName VARCHAR(255);
ALTER TABLE TOURNAMENT
ADD tournamentData VARCHAR(255);
ALTER TABLE TOURNAMENT
ADD category VARCHAR(255);
ALTER TABLE TOURNAMENT
ADD email VARCHAR(255);